# Generated by Django 5.2.7 on 2026-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='product_type',
            field=models.CharField(choices=[('Handmade', 'Handmade'), ('Machine Made', 'Machine Made')], default='Handmade', max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
