# Generated by Django 5.2.7 on 2026-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='custom_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
