# Generated by Django 5.2.7 on 2026-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
