# Generated by Django 5.2.7 on 2026-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_custom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
