# Generated by Django 5.2.7 on 2026-03-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking_estimated_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
    ]
